PictureViewer/PictureViewer/ViewModels/SinglePictureViewModel.cs
using Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PictureViewer.ViewModels
{
    public class SinglePictureViewModel
    {
        public Picture Picture { get; set; }
        public Customer Customer { get; set; }
    }
}

PictureViewer/PictureViewer/Controllers/SinglePictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PictureViewer.ExtensionMethods;
using PictureViewer.Services;
using PictureViewer.ViewModels;

namespace PictureViewer.Controllers
{
    public class SinglePictureController : Controller
    {
        private readonly DatabaseService _databaseService;
        private readonly IMapper _autoMapper;

        public SinglePictureController(DatabaseService databaseService, IMapper autoMapper)
        {
            _databaseService = databaseService;
            _autoMapper = autoMapper;
        }

        // GET: SinglePictureController
        public ActionResult Index()
        {
            return View();
        }

        // GET: SinglePictureController/Details/5
        public ActionResult Details(int id)
        {
            var picture = _databaseService.GetPicture(id);

            var customer = HttpContext.GetCurrentUser();

            if (customer == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var vm = new SinglePictureViewModel()
            {
                Customer = customer,
                Picture = picture
            };

            return View(vm);
        }

        // GET: SinglePictureController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SinglePictureController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SinglePictureController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SinglePictureController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SinglePictureController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var customer = HttpContext.GetCurrentUser();

            if (customer == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var picture = _databaseService.GetPicture(id);

            if(picture.UploaderId == customer.Id)
            {
                await _databaseService.DeletePicture(picture.Id);
            }

            return RedirectToAction("Index", "Pictures");
        }

        // POST: SinglePictureController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PictureViewer/PictureViewer/Views/SinglePicture/Details.cshtml
@model PictureViewer.ViewModels.SinglePictureViewModel
<div>
    @Html.Partial("_NavBar", Model.Customer)
    <div class="single-picture-contaier">
        <img class="single-picture" src="data:image;base64,@System.Convert.ToBase64String(Model.Picture.Image)" />
        <div class="single-picture-details">
            <button class="btn btn-primary button-style single-picture-button single-picture-back" type="button">
                @Html.ActionLink("Back", "Index", "Pictures")
            </button>
            @if (Model.Picture.Uploader.Id == Model.Customer.Id)
            {
                <button class="btn btn-primary button-style single-picture-button single-picture-delete" type="button">
                    @Html.ActionLink("Delete", "Delete", "SinglePicture", new { id = Model.Picture.Id })
                </button>
            }
            <div class="single-picture-info">
                <div class="single-picture-main-text">Title</div>
                <div class="single-picture-description-text">@Model.Picture.Title</div>
                <div class="single-picture-main-text">Description</div>
                <div class="single-picture-description-text">@Model.Picture.Description</div>
            </div>
            <div class="single-picture-uploader-info">
                <div class="single-picture-main-text">Uploader</div>
                <div class="single-picture-description-text">@Model.Picture.Uploader.Username</div>
            </div>
        </div>
    </div>
</div>