PictureViewer/PictureViewer/Controllers/API/DeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PictureViewer.Services;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PictureViewer.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class DeleteController : ControllerBase
    {
        private readonly DatabaseService _databaseService;

        public DeleteController(DatabaseService databaseService)
        {
            _databaseService = databaseService;
        }

        // GET: api/<DeleteController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<DeleteController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<DeleteController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<DeleteController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<DeleteController>/5
        [HttpDelete("{id}")]
        public async Task Delete(int id)
        {
            await _databaseService.DeletePicture(id);

        }
    }
}

PictureViewer/PictureViewer/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Core.Models;
using Core.Models.Input;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PictureViewer.ExtensionMethods;
using PictureViewer.Services;
using PictureViewer.ViewModels;

namespace PictureViewer.Controllers
{
    public class UploadController : Controller
    {

        private readonly DatabaseService _databaseService;
        private readonly IMapper _autoMapper;

        public UploadController(DatabaseService databaseService, IMapper autoMapper)
        {
            _databaseService = databaseService;
            _autoMapper = autoMapper;
        }

        // GET: UploadController
        public ActionResult Index()
        {
            return View();
        }

        // GET: UploadController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UploadController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UploadController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UploadViewModel uploadViewModel)
        {
            try
            {
                byte[] array;

                if(uploadViewModel.Picture == null)
                {
                    throw new Exception();
                }

                using (MemoryStream ms = new MemoryStream())
                {
                    await uploadViewModel.Picture.CopyToAsync(ms);
                    array = ms.ToArray();
                }

                var customerId = HttpContext.GetCurrentUserId();

                if(customerId == null)
                {
                    return RedirectToAction("Index", "Login");
                }

                var pictureDto = new PictureInputDto(uploadViewModel.Title, uploadViewModel.Description, array);

                var picture = _autoMapper.Map<Picture>(pictureDto);

                await _databaseService.AddPicture(customerId.Value, picture);

                return RedirectToAction("Index", "Pictures");
            }
            catch(Exception e)
            {
                uploadViewModel.Failed = true;
                return View("Index", uploadViewModel);
            }
        }

        // GET: UploadController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UploadController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UploadController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UploadController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

PictureViewer/PictureViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PictureViewer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*

        <ul class="navbar-nav flex-grow-1">
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Pictures" asp-action="Index">Pictures</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                           </li>
                       </ul>
    *@
    <div> 
        @RenderBody()
    </div>
</body>
</html>

PictureViewer/PictureViewer/Views/Shared/_NavBar.cshtml
@model Core.Models.Customer 
<div class="navbar-root">
    <div class="navbar-title">
        PictureViewer
    </div>
    <div class="navbar-buttons">
        <div class="navbar-welcome">
            Welcome @Model.Username!
        </div>
        <button class="btn btn-primary button-style">@Html.ActionLink("Delete User", "Delete", "Login")</button>
        <button class="btn btn-primary button-style">@Html.ActionLink("Upload Picture", "Index", "Upload")</button>
        <button class="btn btn-primary button-style">@Html.ActionLink("Sign out", "SignOut", "Login")</button>
    </div>
</div>