PictureViewer/PictureViewer/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PictureViewer.ExtensionMethods;
using PictureViewer.Services;
using PictureViewer.ViewModels;

namespace PictureViewer.Controllers
{
    public class PicturesController : Controller
    {
        private readonly DatabaseService _databaseService;
        private readonly IMapper _autoMapper;

        public PicturesController(DatabaseService databaseService, IMapper autoMapper)
        {
            _databaseService = databaseService;
            _autoMapper = autoMapper;
        }

        // GET: PicturesController
        public ActionResult Index()
        {
            if (!HttpContext.IsSignedIn())
            {
                return RedirectToAction("Index", "Login");
            }

            var customer = HttpContext.GetCurrentUser();

            if(customer == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var vm = new PicturesViewModel()
            {
                Customer = customer,
                Pictures = _databaseService.GetPictures().ToList()
            };

            return View(vm);
        }

        // GET: PicturesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PicturesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PicturesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PicturesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PicturesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PicturesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PicturesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PictureViewer/PictureViewer/Views/Update/Index.cshtml
@model PictureViewer.ViewModels.UploadViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="login-root">

    <div class="login-title">Welcome to the Picture Viewer!</div>

    @using (Html.BeginForm("Update", "Update", FormMethod.Post, new { @class = "login-form", enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Title)
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control login-input" })
            @if (Model != null && Model.Failed)
            {
                @Html.ValidationMessageFor(m => m.Title, "Title required", new { style = "color: red;" })
            }
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description)
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control login-input" })
        </div>
        <div class="form-file">
            <input class="file-input" asp-for="Picture" id="customFile" type="file">
        </div>

        @Html.AntiForgeryToken()
        <button class="btn btn-primary" type="submit">Upload</button>
    }

    <button class="btn btn-primary button-style" type="button">
        @Html.ActionLink("Back", "Index", "Pictures")
    </button>


    @if (Model != null && Model.Failed)
    {
        <div class="alert alert-danger" style="margin: 8px;">Something went wrong</div>
    }

</div>

<script type="text/javascript">

        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
</script>